extends: default

rules:
  line-length: disable
  document-start: disable
  truthy:
    level: warning
  braces: disable
  colons: disable
  commas: disable
  trailing-spaces: disable

  indentation:
    level: warning

  comments:
    level: warning
