name: Format

on:
  pull_request: {}

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check formatting
        shell: bash
        run: |
          set -e
          BASE_REF=${{ github.base_ref }}
          git fetch origin "$BASE_REF":"refs/remotes/origin/$BASE_REF"
          CHANGED=$(git diff --name-only "origin/$BASE_REF"... | grep -E '\.(c|cc|cpp|cxx|h|hh|hpp)$' || true)
          if [ -z "$CHANGED" ]; then 
            echo "No C/C++ changes"
            exit 0
          fi
          clang-format -n --Werror $CHANGED
