name: Nightly

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@v4

      - uses: jurplel/install-qt-action@v3
        with:
          version: "6.6.3"
          arch: linux_gcc_64
          modules: "qt5compat qtimageformats qtmultimedia"

      - name: Skip if no CMake project
        shell: bash
        run: |
          if [ ! -f CMakeLists.txt ]; then
            echo "No CMakeLists.txt. Skipping nightly build."
            exit 0
          fi

      - run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build -j
      - run: ctest --test-dir build --output-on-failure || true
