name: Nightly

on:
  schedule:
    - cron: '0 0 * * *' # daily 00:00 UTC

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: seanmiddleditch/gha-setup-ninja@v4

      - uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.3'
          modules: |
            qt5compat
            qtimageformats
            qtmultimedia

      - run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j
          ctest --test-dir build --output-on-failure || true
