name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            qt: 6.6.3
            qt_arch: linux_gcc_64
          - os: macos-14
            qt: 6.6.3
            qt_arch: macos
          - os: windows-latest
            qt: 6.6.3
            qt_arch: win64_msvc2022_64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@v4
      - uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt }}
          arch: ${{ matrix.qt_arch }}
          modules: |
            qt5compat
            qtimageformats
            qtmultimedia

      - run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build -j

      - name: Package per OS
        shell: bash
        run: |
          APP=ediky_editor
          mkdir -p dist
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            7z a dist/${APP}-windows.zip ./build/*
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            zip -r dist/${APP}-macos.zip ./build || true
          else
            tar czf dist/${APP}-linux.tar.gz -C build .
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
